/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/yaml"

	agentv1alpha1 "github.com/gke-labs/kube-agents/k8s-operator/api/v1alpha1"
)

// a2aGatewayIngressFixturePath is the A2A gateway's rendered ingress surface
// with both doors armed: its two NetworkPolicies and the gateway container's
// declared ports, nothing else. The conformance suite reads it
// (tests/conformance, C1) to hold the policies to "the collector, on the
// metrics port, and nobody else": the suite cannot run Go, and no golden
// renders mode next, so this file is the contract between the two.
//
// Regenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update
const a2aGatewayIngressFixturePath = "testdata/a2a-gateway-ingress.yaml"

// a2aGatewayIngressFixtureHeader opens the fixture, so a reader who finds it
// knows it is generated and from where.
const a2aGatewayIngressFixtureHeader = "# Generated by TestRenderedA2AGatewayIngressMatchesTheConformanceFixture\n" +
	"# (k8s-operator/internal/controller/platformagent_a2a_gateway_metrics_test.go)\n" +
	"# with A2A_INJECT_BACKEND and A2A_AGENT_DOOR on. Read by tests/conformance.\n" +
	"# Regenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update\n"

// a2aGatewayMetricsEnvtestNamespace is the namespace the envtest case renders into.
const a2aGatewayMetricsEnvtestNamespace = "a2a-gateway-metrics"

// a2aGatewayDoorPorts is the gateway container's ports without the metrics
// listener's: what the door tests count.
func a2aGatewayDoorPorts(ports []corev1.ContainerPort) []corev1.ContainerPort {
	var doors []corev1.ContainerPort
	for _, p := range ports {
		if p.Name != a2aGatewayMetricsPortName {
			doors = append(doors, p)
		}
	}
	return doors
}

// assertA2AGatewayFenceAdmitsOnlyTheCollector holds one gateway fence to
// exactly one ingress rule: from the gke-gmp-system namespace by its
// metadata.name label, no pod selector and no ipBlock beside it, to TCP
// a2aGatewayMetricsPort and no other port.
func assertA2AGatewayFenceAdmitsOnlyTheCollector(t *testing.T, np *networkingv1.NetworkPolicy) {
	t.Helper()
	if len(np.Spec.Ingress) != 1 {
		t.Fatalf("%s carries %d ingress rules, want exactly the collector's: %+v", np.Name, len(np.Spec.Ingress), np.Spec.Ingress)
	}
	rule := np.Spec.Ingress[0]
	if len(rule.From) != 1 {
		t.Fatalf("%s's rule admits %d peers, want the collector's namespace alone: %+v", np.Name, len(rule.From), rule.From)
	}
	peer := rule.From[0]
	if peer.PodSelector != nil || peer.IPBlock != nil || peer.NamespaceSelector == nil {
		t.Errorf("%s's peer is %+v, want a namespace selector and nothing else", np.Name, peer)
	} else if len(peer.NamespaceSelector.MatchExpressions) != 0 ||
		!reflect.DeepEqual(peer.NamespaceSelector.MatchLabels, map[string]string{labelMetadataName: gmpNamespace}) {
		t.Errorf("%s admits namespaces %+v, want %s=%s alone", np.Name, peer.NamespaceSelector, labelMetadataName, gmpNamespace)
	}
	if len(rule.Ports) != 1 || rule.Ports[0].Protocol == nil || *rule.Ports[0].Protocol != corev1.ProtocolTCP ||
		rule.Ports[0].Port == nil || rule.Ports[0].Port.IntValue() != int(a2aGatewayMetricsPort) || rule.Ports[0].EndPort != nil {
		t.Errorf("%s's rule opens %+v, want TCP %d alone", np.Name, rule.Ports, a2aGatewayMetricsPort)
	}
}

// TestTheA2AGatewayDeclaresItsMetricsListener: whatever backend the gateway
// starts on, its container declares the metrics port once under its name and
// carries A2A_METRICS_PORT at the same number, so the listener, the scrape and
// the ingress rule cannot name different ports.
func TestTheA2AGatewayDeclaresItsMetricsListener(t *testing.T) {
	chat := gchatTestAgent("next", true)
	if !a2aChatArmed(chat) {
		t.Fatal("the gchat case does not arm Chat on the gateway; it would test the Discord render twice")
	}
	cases := []struct {
		name  string
		agent *agentv1alpha1.PlatformAgent
		doors bool
	}{
		{"discord", a2aTestAgent(), false},
		{"gchat", chat, false},
		{"both doors", a2aTestAgent(), true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.doors {
				t.Setenv(a2aInjectBackendEnvVar, "true")
				t.Setenv(a2aAgentDoorEnvVar, "true")
			}
			c := buildA2AGatewayDeployment(tc.agent).Spec.Template.Spec.Containers[0]
			var ports []corev1.ContainerPort
			for _, p := range c.Ports {
				if p.Name == a2aGatewayMetricsPortName || p.ContainerPort == a2aGatewayMetricsPort {
					ports = append(ports, p)
				}
			}
			if len(ports) != 1 || ports[0].Name != a2aGatewayMetricsPortName || ports[0].ContainerPort != 9096 {
				t.Fatalf("want exactly one %s container port on 9096, got %+v", a2aGatewayMetricsPortName, c.Ports)
			}
			var found []corev1.EnvVar
			for _, e := range c.Env {
				if e.Name == "A2A_METRICS_PORT" {
					found = append(found, e)
				}
			}
			if len(found) != 1 || found[0].Value != "9096" {
				t.Fatalf("want exactly one A2A_METRICS_PORT=9096, got %+v", found)
			}
			for _, p := range a2aGatewayDoorPorts(c.Ports) {
				if p.ContainerPort == a2aGatewayMetricsPort {
					t.Errorf("door port %+v shares the metrics port", p)
				}
			}
		})
	}
}

// TestTheA2AGatewayFenceMirrorsTheBrokersCollectorRule: the gateway's one
// ingress rule is the credential broker's second rule with the gateway's
// metrics port in it, the same peer byte for byte, on both fences (the
// inject door's and the A2A door's copy).
func TestTheA2AGatewayFenceMirrorsTheBrokersCollectorRule(t *testing.T) {
	agent := a2aTestAgent()
	broker := buildCredentialProxyNetworkPolicy(brokerPodAgent())
	if len(broker.Spec.Ingress) != 2 {
		t.Fatalf("the broker's policy has %d rules; this test compares against its second, the collector's", len(broker.Spec.Ingress))
	}
	collector := broker.Spec.Ingress[1]
	for _, np := range []*networkingv1.NetworkPolicy{buildA2AGatewayNetworkPolicy(agent), buildA2ADoorNetworkPolicy(agent)} {
		t.Run(np.Name, func(t *testing.T) {
			assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
			if !reflect.DeepEqual(np.Spec.Ingress[0].From, collector.From) {
				t.Errorf("the gateway admits %+v, the broker admits %+v; the collector rule is the broker's copied", np.Spec.Ingress[0].From, collector.From)
			}
		})
	}
}

// TestRenderedA2AGatewayIngressMatchesTheConformanceFixture keeps the fixture
// the conformance suite reads equal to what the operator renders.
func TestRenderedA2AGatewayIngressMatchesTheConformanceFixture(t *testing.T) {
	t.Setenv(a2aInjectBackendEnvVar, "true")
	t.Setenv(a2aAgentDoorEnvVar, "true")
	agent := a2aTestAgent()
	dep := buildA2AGatewayDeployment(agent)
	trimmed := &appsv1.Deployment{
		TypeMeta:   dep.TypeMeta,
		ObjectMeta: metav1.ObjectMeta{Name: dep.Name, Namespace: dep.Namespace},
	}
	for _, c := range dep.Spec.Template.Spec.Containers {
		trimmed.Spec.Template.Spec.Containers = append(trimmed.Spec.Template.Spec.Containers,
			corev1.Container{Name: c.Name, Ports: c.Ports})
	}
	var docs []string
	for _, obj := range []any{buildA2AGatewayNetworkPolicy(agent), buildA2ADoorNetworkPolicy(agent), trimmed} {
		out, err := yaml.Marshal(obj)
		if err != nil {
			t.Fatal(err)
		}
		docs = append(docs, string(out))
	}
	rendered := a2aGatewayIngressFixtureHeader + "---\n" + strings.Join(docs, "---\n")

	path := filepath.Clean(a2aGatewayIngressFixturePath)
	if *updateAuthMapFixture {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(rendered), 0o644); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the fixture: %v\nRegenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update", err)
	}
	if string(want) != rendered {
		t.Errorf("the rendered gateway ingress and the fixture the conformance suite reads have diverged.\nRegenerate with: go test ./internal/controller/ -run TestRenderedA2AGatewayIngress -update\n--- fixture\n%s\n--- rendered\n%s", want, rendered)
	}
}

// TestTheA2AGatewayMetricsSurfaceOnTheAPIServerEnvtest applies the gateway
// Deployment and the fences the way reconcileA2A does, against a real API
// server, and reads back what it accepted: the metrics port and env on the
// container, and on each fence the collector rule alone.
func TestTheA2AGatewayMetricsSurfaceOnTheAPIServerEnvtest(t *testing.T) {
	cl, scheme := startEnvtest(t)
	ctx := context.Background()
	t.Setenv(a2aInjectBackendEnvVar, "true")
	t.Setenv(a2aAgentDoorEnvVar, "true")
	if err := cl.Create(ctx, &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: a2aGatewayMetricsEnvtestNamespace}}); err != nil {
		t.Fatalf("creating namespace: %v", err)
	}
	agent := a2aTestAgent()
	agent.Namespace = a2aGatewayMetricsEnvtestNamespace
	agent.UID = types.UID("a2a-gateway-metrics-uid")
	r := &PlatformAgentReconciler{Client: cl, APIReader: cl, Scheme: scheme}

	if err := r.reconcileA2ANetworkFences(ctx, agent); err != nil {
		t.Fatalf("reconcileA2ANetworkFences: %v", err)
	}
	if err := r.applyA2AGatewayDeployment(ctx, agent, buildA2AGatewayDeployment(agent)); err != nil {
		t.Fatalf("applyA2AGatewayDeployment: %v", err)
	}

	dep := &appsv1.Deployment{}
	if err := cl.Get(ctx, client.ObjectKey{Name: a2aGatewayName(agent), Namespace: agent.Namespace}, dep); err != nil {
		t.Fatalf("the API server holds no gateway Deployment: %v", err)
	}
	c := dep.Spec.Template.Spec.Containers[0]
	var metricsPorts []corev1.ContainerPort
	for _, p := range c.Ports {
		if p.Name == a2aGatewayMetricsPortName {
			metricsPorts = append(metricsPorts, p)
		}
	}
	if len(metricsPorts) != 1 || metricsPorts[0].ContainerPort != a2aGatewayMetricsPort || metricsPorts[0].Protocol != corev1.ProtocolTCP {
		t.Errorf("the accepted gateway declares %+v, want one TCP %s on %d", c.Ports, a2aGatewayMetricsPortName, a2aGatewayMetricsPort)
	}
	env := envMapOf(c.Env)
	if got := env[a2aGatewayMetricsPortEnvVar].Value; got != strconv.Itoa(int(a2aGatewayMetricsPort)) {
		t.Errorf("the accepted gateway carries %s=%q, want %d", a2aGatewayMetricsPortEnvVar, got, a2aGatewayMetricsPort)
	}

	for _, name := range []string{a2aInjectName(agent), a2aDoorName(agent)} {
		np := &networkingv1.NetworkPolicy{}
		if err := cl.Get(ctx, client.ObjectKey{Name: name, Namespace: agent.Namespace}, np); err != nil {
			t.Fatalf("the API server holds no fence %s: %v", name, err)
		}
		assertA2AGatewayFenceAdmitsOnlyTheCollector(t, np)
	}
}
